project:
  type: website
  output-dir: docs
  resources:
    - soc33-sum23-syllabus.pdf

website:
  page-navigation: true
  title: "SOCIOL 333"
  description: "Homepage for SOCIOL 333 - Quantitative Analysis of Sociological Data, Summer 2023 Term 1"
  site-url: "https://soc333-sum23.github.io/"

  repo-url: https://github.com/soc333-sum23/soc333-sum23.github.io
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#32174d" # Russian Violet
    foreground: "#f8f8f8"
    logo: "images/logo.png"
    pinned: true
    align: "center"
    tools:
      - icon: github
        href: https://github.com/soc333-sum23/soc333-sum23.github.io
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: person-fill
        href: https://sakai.duke.edu/portal/directtool/3eb7ea22-0cb1-464a-b496-8f932e5315a0/
        text: "Sakai"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: Schedule
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-links.qmd
            text: Useful links
      - section: "Computing"
        contents:
          - href: computing-setup.qmd
            text: Setup
          - href: computing-clonerepo.qmd
            text: Cloning and committing
          - href: computing-cheatsheets.qmd
            text: Cheatsheets
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: "General information"
          - section: "Instructions"
            contents:
              - href: project-proposal.qmd
                text: "Component 1: Proposal"
              # - href: project-descstats.qmd
              #   text: "Component 2: Descriptive Stats"
              # - href: project-results.qmd
              #   text: "Component 3: Results"
              # - href: project-paper.qmd
              #   text: "Component 4: Paper"
              # - href: project-presentation.qmd
              #   text: "Component 5: Presentation"
          - section: "Examples"
            contents:
              - href: project_example/c1_proposal.qmd
                text: "Component 1: Proposal"
      - section: "Slides"
        contents:
          - href: slides/01-welcome.qmd
            text: "Lecture 1: Welcome"
          - href: slides/02-datavariables.qmd
            text: "Lecture 2: Data and Variables"
          - href: slides/03-computing.qmd
            text: "Lecture 3: Meet the Toolkit"
          - href: slides/04-researchquestions.qmd
            text: "Lecture 4: Project and research questions"
          - href: slides/05-studiessamples.qmd
            text: "Lecture 5: Studies and samples"
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Aidan Combs. Credit to [Mine Çetinkaya-Rundel](https://mine-cr.com/) and her [STA199 course](https://sta199-f22-1.github.io/), on which the materials and website for SOCIOL333 are based"
    background: "#32174d" # Russian Violet
    foreground: "#f8f8f8"

format:
  html:
    theme:
      light: [cosmo, style/sta199.scss]
      dark: [cosmo, style/sta199.scss, style/dark.scss]
    linkcolor: "#32174d" # Russian Violet
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
