project:
  type: website
  output-dir: docs
  resources:
    - sta199-f22-1-syllabus.pdf
    - slides/27-interactive-web-apps.pdf

website:
  page-navigation: true
  title: "SOCIOL 333"
  description: "Homepage for SOCIOL 333 - Quantitative Analysis of Sociological Data, Summer 2023 Term 1"
  site-url: "https://ahcombs.github.io/soc333-sum23.github.io/"

  repo-url: https://github.com/ahcombs/soc333-sum23.github.io
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#325b74" # Pantone Midnight - Fall 2022
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ahcombs/soc333-sum23.github.io
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: person-fill
        href: https://sakai.duke.edu/portal/directtool/3eb7ea22-0cb1-464a-b496-8f932e5315a0/
        text: "Sakai"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing-cheatsheets.qmd
            text: Cheatsheets
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: "General information"
          - href: project-proposal.qmd
            text: "Component 1: Proposal"
          - href: project-descstats.qmd
            text: "Component 2: Descriptive Stats"
          - href: project-results.qmd
            text: "Component 3: Results"
          - href: project-paper.qmd
            text: "Component 4: Paper"
          - href: project-presentation.qmd
            text: "Component 5: Presentation"
          - href: project-tips-resources.qmd
            text: "Tips + resources"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Aidan Combs"
    background: "#325b74" # Pantone Midnight - Fall 2022

format:
  html:
    theme:
      light: [cosmo, style/sta199.scss]
      dark: [cosmo, style/sta199.scss, style/dark.scss]
    linkcolor: "#325b74" # Pantone Midnight - Fall 2022
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
